做完匹配分机制了
Fallen-Breath/tcuhc-fabric pull request #1
Opened 2022-01-15 09:28 UTC by CCSCovenant

2022-01-15 09:56 UTC, CCSCovenant commented
Change:
- 对NORMAL 和 KING的随机分队系统进行修改, 加入MMR匹配分用于平衡组队
   -新增PlayerMatchMakingDataHandler用于处理玩家分数计算,储存和读取
   -玩家分数将会用以下公式计算:
              新分数 = 历史分数*(1-单局权重) + 当局分数*单局权重*连胜系数^连胜数
   -玩家单局分数将会用以下公式计算:
              单局分数 = 伤害/承伤害*伤害值 * 击杀系数^击杀数
   -玩家匹配将把玩家分成n队 Sum (玩家分数^战力系数) 相近的队伍
   -目前的系数值如下
        单局权重:0.2
        连胜系数:1.025
        击杀系数:1.2
        战力系数:1.3
        初始玩家权重:100

2022-01-15 10:01 UTC, CCSCovenant commented
玩家的匹配数据储存在根目录的playerData.txt

目前的匹配机制是将玩家从战力最高排到战力最低, 
从战力最高的玩家开始 ,
选择所有队伍里面最弱的一个队伍, 
将这个玩家加入此队伍
更新所有队伍的分数和

2022-01-15 10:16 UTC, Fallen-Breath commented
还没仔细审实现逻辑，但发现了很多编码规范整洁度相关的东西：

- 请移除所有用于调试的输出语句，即各种 `System.out.println` 等。如果需要保留这些输出，请用 `UhcGameManager#LOG` 来打印日志
- 请不要用自定义的名词缩写来为函数/变量命名，这会导致维护难度上升
- 恰当的空格能有效提升排版整洁度，如 `{` 前，`,` 后
- 如无必要，请使用英文而非中文撰写注释

2022-01-15 10:18 UTC, Fallen-Breath commented
> 玩家的匹配数据储存在根目录的playerData.txt
> 
> 目前的匹配机制是将玩家从战力最高排到战力最低, 从战力最高的玩家开始 , 选择所有队伍里面最弱的一个队伍, 将这个玩家加入此队伍 更新所有队伍的分数和

这一个实现是不涉及任何随机性吗，也就是在给定的数据情况下是否仍有出现不同分队的可能？如果仅仅是通过贪心得出固定的一个分队策略的话，这就不太像是“随机分队”了，而是人为地根据战力“钦定”分队。

2022-01-15 10:18 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/UhcPlayerManager.java
> +			double factor = Math.pow(1.2,playerKill);
魔法常量！不好！

2022-01-15 10:42 UTC, Fallen-Breath commented
关于积分计算方式，分队权重等数值计算公式，我的建议是，先将数据收集部分做好，采集到足够多的样本后，再设计计算分配方法，这样可以有实际数据来测试评价这个算法是否足够优秀。

2022-01-15 10:42 UTC, Fallen-Breath commented
我个人期望的匹配策略：随机分队 k 次，取 k 种分法种某一计算值最优的一队。k 可配置。其值等于 1 时等价于完全随机分队，其值足够大时近似于依据计算值的最优分队，k 取例如 4 时能较为平均又略带随机的分队。

2022-01-16 04:12 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/UhcGameManager.java
> -	public static final Logger LOG = LogManager.getLogger("TC UHC");
不要修改缩进字符

2022-01-16 04:13 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/UhcGameTeam.java
> -public class UhcGameTeam
同上，不要修改缩进符

2022-01-16 12:45 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/UhcGameManager.java
> -	public MinecraftServer getMinecraftServer() { return mcServer; }
如无必要，也不要进行代码格式化

2022-01-16 12:46 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/UhcGameManager.java
> +		//暂停接受UHC regen的指令,计算和更新pp
为何要禁用 regen 指令

2022-01-19 11:24 UTC, CCSCovenant commented on src/main/java/me/fallenbreath/tcuhc/UhcGameManager.java
> +		//暂停接受UHC regen的指令,计算和更新pp
本来想着是防止regen以后丢失MMR/统计数据
不过想想好像也没差

我觉得加上是好的 还没做就是了

2022-01-19 16:54 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/util/PlayerMatchMakingDataHandler.java
> +				playerData.put(uuid, new PlayerMatchMakingData(uuid, 0, 100,player.getName())); //初始的PP值为100
魔法常量 `100` 建议单独拎出来作为一个 private static final

2022-01-19 16:54 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/util/TeamAllocator.java
> +		UhcGameManager.LOG.log(Level.DEBUG,"------------STD result start----------------");
`UhcGameManager.LOG.log(Level.DEBUG)` 可换为 `UhcGameManager.LOG.debug` 以化简

2022-01-21 01:44 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/util/PlayerMatchMakingDataHandler.java
> +				winStreak--;
对于“连胜”这一种数据，是否使用“缓慢上升而快速下降”的实现更为合适？如未胜利时减去更大数值，或者除以 2

2022-01-21 01:46 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/util/TeamAllocator.java
> +		shuffle(incoming_List);
建议使用 `java.util.Collections#shuffle`

2022-01-21 01:47 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/util/TeamAllocator.java
> +	public List<List<UhcGamePlayer>> TotalRandomMatchMaking(Map<UhcGamePlayer, Double> players, int teamNums) {
方法名遵循驼峰命名法呀，下面的 `SamplingMatchmaking` 也是

2022-01-21 04:06 UTC, Fallen-Breath commented
对于一个平均水平的玩家，每一局换血比为 1，杀 1 个人，那他每一局的 PP 值将会是 `1 * 1.2^1 = 1.2`，远小于初始的 PP 值 `100`，这会导致在经过足够多局后，新玩家的 PP 值（接近 100）总会高于老玩家的 PP 值（接近 1）

2022-01-21 04:17 UTC, Fallen-Breath commented
作为计算每局 PP 值的因素，换血效率 `damageDealt / damageTake` 是直接被相乘计入 PP 值，未加任何处理，这是否合适？考虑以下几种情况：

- 决赛圈长时间 PVP，受伤/输出数值不会低，且换血比趋近于个人能力水平。这是我们想要的数据。
- BOSS 模式，多打 1：受伤/输出数值很高，BOSS 的换血效率总是小于 1
- PVP 仅出现在前期，游戏在后期决赛前结束的情况：低甲情况下偷袭成功可得到极高的换血比，受伤/输出数值不高

因此，有以下一些问题：

- 计算换血比时是否需要考虑游戏模式
- 计算换血比时是否需要考虑输出/伤害数值的大小，因为这些值越大，结果越准确
- 换血比是否可以直接作用于 PP 值，是否需要对较大较小值进行一定的函数映射变化，让过大的数值没那么大

2022-01-21 04:19 UTC, Fallen-Breath commented
计算 MMR 的各种参数是否有必要支持配置中的配置？对于这种长期储存收集的数据，在使用过程中修改数据是容易造成已有数据的失真的，并且调整这些参数需要对整个算法有着足够的理解，基本上只有开发运维人员会进行调整。

因此我认为这些参数在确定下来后硬编码进代码即可。

2022-01-21 04:36 UTC, Fallen-Breath commented
关于计算 PP 的参考数据，现在仅选用了与 PVP 相关的三个数值：承受伤害数、造成伤害数、玩家击杀数，但衡量 UHC 中一个玩家的水平并非仅有 PVP 能力。对于 PVP 菜，但会逃跑会收集资源，总能活下来把队友养肥的这种玩家，他们的 PP 值将会很低，但实际实力不容小觑，仅靠连胜方面的权重不一定能拉高他们的 PP 值

2022-01-21 04:36 UTC, Fallen-Breath commented
建议先写出详细的算法逻辑计算流程，不要急着编写代码，否则总是在改来改去。在完善了算法机制后，再去实现代码。

2022-01-21 18:02 UTC, CCSCovenant commented
1. 换血比没乘上伤害值是我傻逼了()
     -对于映射: 目前的考虑是假设 伤害/输出 遵循正态分布，然后再根据平均值进行调整 未实装
2. 考虑到现在BOSS模式BOSS 基本上都是指定BOSS，因此随机BOSS可能暂时并不必要
3. 放入配置中调整是目前方便上线测试的时候对其进行调整设置的 等大家达成共识以后可以硬编码
4. 对于资源收集能力（包括组织度等能力）很难去有一个很好的量化指标. 
5. 对不平衡组队怨念已久, 急着上线()

2022-01-21 18:17 UTC, Fallen-Breath commented
- 请不要在这个专注于匹配机制的 PR 中提交与匹配机制无关的 commit
- 在本 mod 实现完善的多语言翻译机制前，请使用英文

2022-01-21 18:20 UTC, Fallen-Breath commented
急着上线并不是粗制滥造的理由，随便写一坨奥利给糊上去只会导致日后花更多的时间边挨骂边擦自己的屁股

> 对于一个平均水平的玩家，每一局换血比为 1，杀 1 个人，那他每一局的 PP 值将会是 `1 * 1.2^1 = 1.2`，远小于初始的 PP 值 `100`，这会导致在经过足够多局后，新玩家的 PP 值（接近 100）总会高于老玩家的 PP 值（接近 1），显然这不是我们想要的。

譬如这一条回复所提及的内容，是一个可能直接导致这个匹配机制工作异常的问题，这是得好好解决的

2022-01-21 18:23 UTC, CCSCovenant commented
> 急着上线并不是粗制滥造的理由，随便写一坨奥利给糊上去只会导致日后花更多的时间边挨骂边擦自己的屁股
> 
> > 对于一个平均水平的玩家，每一局换血比为 1，杀 1 个人，那他每一局的 PP 值将会是 `1 * 1.2^1 = 1.2`，远小于初始的 PP 值 `100`，这会导致在经过足够多局后，新玩家的 PP 值（接近 100）总会高于老玩家的 PP 值（接近 1），显然这不是我们想要的。
> 
> 譬如这一条回复所提及的内容，是一个可能直接导致这个匹配机制工作异常的问题，这是得好好解决的

本来这个的计算是伤害*(伤害比) 然后我傻了忘记乘伤害了

2022-01-21 18:30 UTC, Fallen-Breath commented
> > 急着上线并不是粗制滥造的理由，随便写一坨奥利给糊上去只会导致日后花更多的时间边挨骂边擦自己的屁股
> > > 对于一个平均水平的玩家，每一局换血比为 1，杀 1 个人，那他每一局的 PP 值将会是 `1 * 1.2^1 = 1.2`，远小于初始的 PP 值 `100`，这会导致在经过足够多局后，新玩家的 PP 值（接近 100）总会高于老玩家的 PP 值（接近 1），显然这不是我们想要的。
> > 
> > 
> > 譬如这一条回复所提及的内容，是一个可能直接导致这个匹配机制工作异常的问题，这是得好好解决的
> 
> 本来这个的计算是伤害*(伤害比) 然后我傻了忘记乘伤害了

那这是否意味着，对于平均水平的玩家，若一局中打出小于 100 伤害，则 PP 将会低于初始 PP 值；若高于 100 伤害则 PP 值将高于 100。这里直接将一个玩家的期望 PP 值与游戏中的伤害造成数直接挂钩，是否稳妥？因为一局的造成伤害值是受到多种方面影响变化的，这会导致一个技术能力稳定的玩家的 PP 值总会上下浮动而非趋于稳定，引入了更多的与技术水平无关的变量

2022-01-21 18:31 UTC, Fallen-Breath requested changes

2022-01-21 18:31 UTC, Fallen-Breath commented on src/main/java/me/fallenbreath/tcuhc/UhcGameCommand.java
> +				then(literal("cancelStart").requires(UhcGameCommand::isOp).executes(c -> executeCancelStart(c.getSource()))).
https://github.com/Fallen-Breath/tcuhc-fabric/pull/1#issuecomment-1018750044

2022-01-21 18:43 UTC, CCSCovenant commented
rue 我换个分支浇这个PR

2022-01-21 18:43 UTC, closed without merging